### PR TITLE
Edit functionality to edit the tags in the ContentRepository

### PR DESCRIPTION
**Pull request by okkevdeijk**
This is the code change for the functionality I suggested in the [issue ](https://github.com/Geta/Tags/issues/55)I created for Geta Tags. You are more than welcome for suggestions how to improve this code. Thanks in advance!

### CODE REVIEW

**Comment by okkevdeijk** [comment]
Checks are failing, I thought it was because of the Castle.Core packages, but it's not. Someone suggest or check why the tests are failing?

**Comment by okkevdeijk** [comment]
According to the great feedback of @patkleef I made a checkbox and optimized the code. Thanks!

**Comment by patkleef** [comment]
Hi @okkevdeijk, 

I tried your code locally, but after editing a tag it doesn't seem to update page properties. Can you maybe double check if it works for you?

**Comment by okkevdeijk** [comment]
Checked it with a new Epi solution and a clean clone of my git fork repository and it works for me! I am using the local NuGet package that is being generated when you build the solution (in the /bin folder). It works for the tags on pages. You need to publish the page with the tags first...

**Comment by okkevdeijk** [comment]
@patkleef Have you tried it again as well?

**Comment by patkleef** [comment]
Hi @okkevdeijk,

I think I figured out why it's not working for me. The GetaTags attribute is not mandatory when defining tags properties.

`
[UIHint("Tags")]
public virtual string PropertyWithoutGetaTagsAttribute { get; set; }

[UIHint("Tags")]
[GetaTags(AllowSpaces = true, AllowDuplicates = true, CaseSensitive = false)]
public virtual string PropertyWithGetaTagsAttribute { get; set; }
`
Currently, only the properties are updated that are decorated with the GetaTags property.

**before**
image

**after**
image

**Comment by okkevdeijk** [comment]
Thanks for your feedback @patkleef ! Code changed to fix this.

**Pull request merged**
